type: cluster

replicaCount: 3

image:
  repository: nacos/nacos-server
  pullPolicy: IfNotPresent
  tag: "v2.2.3"
  # mysql模式下需要自动创建数据库，非mysql不会生效
  DBInitImage: mysql/mysql-client:8.4.0

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

volume:
  enabled: true
  storageSize: 1Gi
  storageClassName: local-path

# database:
#   type: embedded
database:
  type: mysql
  dbHost: "mysql.db.svc.cluster.local"
  dbPort: 3306
  dbUser: root
  dbName: nacos
  dbPassword: "Abc!@#135"

resources:
  limits:
    cpu: 1000m
    memory: 2048Mi
  requests:
    cpu: 100m
    memory: 2048Mi

config: |
  management.endpoints.web.exposure.include=*

certification:
    enabled: true

nodeSelector: {}

tolerations: []

affinity: {}
