apiVersion: nacos.io/v1alpha1
kind: Nacos
metadata:
  name: {{ include "nacos.fullname" . }}
spec:
  # standalone/cluster
  type: {{ .Values.type}}
  image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
  DBInitImage: {{ .Values.image.DBInitImage }}
  enableEmbedded: {{ .Values.enableEmbedded }}
  replicas: {{ .Values.replicaCount}}
  {{- with .Values.nodeSelector }}
  nodeSelector:
  {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.affinity }}
  affinity:
  {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.tolerations }}
  tolerations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.resources }}
  resources:
  {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.env }}
  env:
  {{- toYaml . | nindent 4 }}
  {{- end }}
  {{-  if .Values.database }}
  database:
    type: {{ .Values.database.type}}
    DBHost: {{ .Values.database.dbHost}}
    DBName: {{ .Values.database.dbName}}
    DBUser: {{ .Values.database.dbUser}}
    DBPort: "{{ .Values.database.dbPort}}"
    DBPassword: "{{ .Values.database.dbPassword}}"
  {{-  end }}
  {{-  if  eq .Values.volume.enabled true}}
  volume:
    enabled: {{ .Values.volume.enabled}}
    requests:
      storage: {{ .Values.volume.storageSize}}
    storageClass: {{ .Values.volume.storageClassName}}
  {{-  end }}
  config: |
{{- if .Values.config }}
{{ .Values.config | indent 4 }}
{{- end }}
