apiVersion: nacos.io/v1alpha1
kind: Nacos
metadata:
  name: nacos
  namespace: nacos
spec:
  type: cluster
  image: mapper-node1:30001/nacos/nacos-server:v2.2.3
  replicas: 3
  resources:
    requests:
      cpu: 100m
      memory: 512Mi
    limits:
      cpu: 1
      memory: 2Gi
  DBInitImage: "mapper-node1:30001/mysql-client:10.2.15-r0"
  database:
    type: mysql
    DBHost: mysql-headless.nacos.svc.cluster.local
    DBName: nacos
    DBUser: root
    DBPort: "3306"
    DBPassword: "Abc!@#135"
  config: |
    management.endpoints.web.exposure.include=*
