apiVersion: nacos.io/v1alpha1
kind: Nacos
metadata:
  name: nacos
  namespace: nacos
spec:
  type: cluster
  image: mapper-node1:30001/nacos/nacos-server:v2.2.3-pgsql
  replicas: 3
  resources:
    requests:
      cpu: 100m
      memory: 512Mi
    limits:
      cpu: 1
      memory: 2Gi
  DBInitImage: "mapper-node1:30001/psql:14.11"
  database:
    type: postgresql
    DBHost: postgresql-hl.nacos.svc.cluster.local
    DBName: nacos
    DBUser: postgres
    DBPort: "5432"
    DBPassword: "Abc!@#135"
  config: |
    management.endpoints.web.exposure.include=*
